# Generated by Django 5.2.6 on 2025-10-01 02:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('shoes', 'Shoes'), ('balls', 'Balls'), ('jerseys', 'Jerseys'), ('socks', 'Socks'), ('shorts', 'Shorts')], default='balls')),
                ('is_featured', models.BooleanField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
