# Generated by Django 5.2.6 on 2025-09-22 13:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('shoes', 'Shoes'), ('balls', 'Balls'), ('jerseys', 'Jerseys'), ('socks', 'Socks'), ('shorts', 'Shorts')], default='balls')),
                ('is_featured', models.BooleanField()),
            ],
        ),
    ]
